### ISSUE TITLE
pipy source issue

### ISSUE THREAD

**Issue by justin-petermann** [brunoalano/aiowhois#1]
Hi,

when i try to install it by pip3: 
```
$ pip3 install aiowhois
Collecting aiowhois
  Using cached https://files.pythonhosted.org/packages/9e/7c/c8e95b123ac8c8f24206fc7a32c2baf8cde29d2d88d07dfb9973c764746d/aiowhois-0.1.0.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 928, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 741, in unpack_file
    untar_file(filename, location)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 707, in untar_file
    shutil.copyfileobj(fp, destfp)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
AttributeError: 'NoneType' object has no attribute 'read'
```
 > additionnals informations : exemple on OSX 10.14.6 but too in debian/buster python3.7
```
$ pip3 --version
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ python3 --version
Python 3.7.1
```

**Comment by TechOtter** [comment]
Having the same problem.
pip 19.3.1
Python 3.7.4

**Comment by TechOtter** [comment]
Out of curiosity I downloaded the tarball and did a `pip install .` after exploding it. It install that way, but this warning showed up in the process

> WARNING: Ignoring special file error '`../aiowhois-0.1.0/aiowhois/data/.notifier` is a named pipe' encountered copying ../aiowhois-0.1.0/aiowhois/data/.notifier to /var/folders/_n/lybftmq54dzfgqz8q_6bj1140000gq/T/pip-req-build-zo71g37m/aiowhois/data/.notifier.

> 

double checking the tar file I could see the name pipe. Trying a `pip install aiowhois-0.1.0.tar.gz` resulted in the same exception. Expanding the archive, removing the named pipe, re-taring it, and then installing from the new tar file succeeded. Looks like the named pipe is the problem.
